{
 "title": "switchboard metrics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Average Log Age",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) (switchboard_log_age_sum[5m]/switchboard_log_age_count[5m])"
    }
   ]
  },
  {
   "title": "Average Job Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster) ((switchboard_total_latency_total[5m]/switchboard_job_posting_total[5m] )/count(switchboard_total_latency_total[5m]))"
    }
   ]
  },
  {
   "title": "Scheduler Funds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scheduler_node_balance*0.000000001"
    }
   ]
  },
  {
   "title": "Node Balances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(switchboard_node_balance) by (account)"
    }
   ]
  },
  {
   "title": "save result failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (errorType) (rate(switchboard_save_result_failure_total[5m]))"
    }
   ]
  },
  {
   "title": "insufficient aggregation error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster,pod) (rate(switchboard_node_aggregation_insufficient_responses_total[5m]))"
    }
   ]
  },
  {
   "title": "job failure percentage rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster,pod) (rate(switchboard_job_failure_total[5m])/(rate(switchboard_job_success_total[5m])+rate(switchboard_job_failure_total[5m])))"
    }
   ]
  },
  {
   "title": "heartbeat failure rate",
   "type": "graph",
   "description": "y axis is failures per 5 minute increment",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cluster,pod) (rate(switchboard_heartbeat_failure_total[5m]))"
    }
   ]
  }
 ]
}