# syntax=docker/dockerfile:1.4
FROM switchboardlabs/sgx-function AS builder


ARG CARGO_NAME=switchboard-function

WORKDIR /home/root/solana-sdk

COPY ./rust/switchboard-common/Cargo.toml \
     ./rust/switchboard-common/Cargo.lock \
     ./rust/switchboard-common/

COPY ./rust/switchboard-solana/Cargo.toml \
     ./rust/switchboard-solana/Cargo.lock \
     ./rust/switchboard-solana/

COPY ./examples/functions/03_candles_oracle/Cargo.toml \
     ./examples/functions/03_candles_oracle/Cargo.lock \
     ./examples/functions/03_candles_oracle/

COPY ./examples/functions/03_candles_oracle/switchboard-function/Cargo.toml \
     ./examples/functions/03_candles_oracle/switchboard-function/Cargo.lock \
     ./examples/functions/03_candles_oracle/switchboard-function/

COPY ./rust/switchboard-common/src \
     ./rust/switchboard-common/src/

COPY ./rust/switchboard-solana/src \
     ./rust/switchboard-solana/src/

COPY ./examples/functions/03_candles_oracle/src \
     ./examples/functions/03_candles_oracle/src/

COPY ./examples/functions/03_candles_oracle/switchboard-function/src \
     ./examples/functions/03_candles_oracle/switchboard-function/src/

WORKDIR /home/root/solana-sdk/examples/functions/03_candles_oracle/switchboard-function

RUN --mount=type=cache,target=/usr/local/cargo/registry,id=${TARGETPLATFORM} --mount=type=cache,target=target,id=${TARGETPLATFORM} \
    cargo build --release && \
    cargo strip && \
    mv /home/root/solana-sdk/examples/functions/03_candles_oracle/switchboard-function/target/release/${CARGO_NAME} /sgx

FROM switchboardlabs/sgx-function

# Copy the binary
WORKDIR /sgx
COPY --from=builder /sgx/${CARGO_NAME} /sgx/app

# Get the measurement from the enclave
RUN /get_measurement.sh
ENTRYPOINT ["bash", "/boot.sh"]
