module.exports = {
  tutorialSidebar: [
    {
      type: "doc",
      label: "Overview",
      id: "api",
    },
    {
      type: "doc",
      label: "Switchboard Tasks",
      id: "switchboard-tasks",
    },
    {
      type: "category",
      label: "Clients",
      collapsible: false,
      items: [
        {
          type: "link",
          label: "Typescript",
          href: "https://docs.switchboard.xyz/api/ts/",
        },
        {
          type: "link",
          label: "Typescript Lite",
          href: "https://docs.switchboard.xyz/api/ts-lite/",
        },
        {
          type: "link",
          label: "Sbv2 Utils",
          href: "https://docs.switchboard.xyz/api/sbv2-utils/",
        },
        {
          type: "link",
          label: "Python",
          href: "https://docs.switchboard.xyz/api/py/",
        },
        {
          type: "link",
          label: "Rust",
          href: "https://docs.rs/switchboard-v2/latest/switchboard_v2/",
        },
      ],
    },
    {
      type: "category",
      label: "CLI",
      items: [
        {
          type: "autogenerated",
          dirName: "cli",
        },
      ],
    },
  ],
};
