/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  tutorialSidebar: [
    {
      type: "doc",
      label: "Overview",
      id: "api",
    },
    {
      type: "doc",
      label: "Switchboard Tasks",
      id: "switchboard-tasks",
    },
    {
      type: "category",
      label: "Libraries",
      collapsed: true,
      collapsible: false,
      items: [
        {
          type: "link",
          label: "Typescript",
          href: "https://docs.switchboard.xyz/api/ts",
        },
        {
          type: "link",
          label: "Typescript Lite",
          href: "https://docs.switchboard.xyz/api/ts-lite",
        },
        {
          type: "link",
          label: "Python",
          href: "https://docs.switchboard.xyz/api/py",
        },
        {
          type: "link",
          label: "Rust",
          href: "https://docs.rs/switchboard-v2/latest/switchboard_v2/",
        },
      ],
    },
    {
      type: "category",
      label: "CLI",
      items: [
        {
          type: "autogenerated",
          dirName: "switchboardv2-cli",
        },
      ],
    },
  ],
};
